/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/system': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get daemon runtime/configuration summary. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description System status. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SystemResponse'];
          };
        };
        401: components['responses']['Unauthorized'];
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/system/import-export-scheduler/recommendation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Inspect live import/export scheduling capacity and estimate representative concurrency.
     * @description The recommendation is a conservative resource model, not a measured throughput guarantee. A result of zero means the live memory budget cannot safely fit one modelled job and must not be coerced to one. CPU and I/O are concurrency weights; a memory-safe job that exceeds either whole weight budget may run only as one isolated job. A compressed logical import is charged at the configured prepared-data ceiling because its expansion ratio is not trusted before bounded extraction; compressed Redis, Valkey, and Qdrant physical imports are charged at the target disk allocation, capped by the physical archive limit. MongoDB, Redis, Valkey, and Qdrant are always modelled as natively compressed. action=export with mode=wipe is invalid.
     */
    get: {
      parameters: {
        query?: {
          /** @description Defaults to postgres when omitted. */
          protocol?: components['schemas']['Protocol'];
          action?: 'import' | 'export';
          /** @description Plain or prepared input size. Defaults to the configured maximum upload size. */
          size_bytes?: number;
          /** @description Defaults to size_bytes rounded up to MiB. */
          target_disk_mib?: number;
          mode?: 'merge' | 'wipe';
          /** @description Compression hint. Native-compression protocols are treated as compressed even when false. */
          compressed?: boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Live scheduler snapshot and model-based recommendation. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ImportExportSchedulerRecommendation'];
          };
        };
        401: components['responses']['Unauthorized'];
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/system/config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Merge a validated config patch into the daemon config file.
     * @description Writes config.yml and returns restart_required=true. Refuses uuid, token_id, and token edits. The allocation.prevent_cpu_overallocation, allocation.prevent_memory_overallocation, and allocation.prevent_disk_overallocation booleans may be changed independently; all default to true.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Config patch applied. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConfigPatchResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    trace?: never;
  };
  '/api/heartbeat': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lightweight authenticated API liveness check.
     * @description Returns success when the authenticated management API is reachable, independently of database instance and gateway readiness.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Heartbeat response. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HeartbeatResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/metrics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Prometheus metrics for the daemon. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Prometheus text exposition. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': string;
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List database instances with their live classified container statuses. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Instance list. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Instance'][];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    /** Create a database instance. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateInstanceRequest'];
        };
      };
      responses: {
        /** @description Instance creation accepted and continuing in the background. */
        202: {
          headers: {
            /** @description Origin-relative instance creation status URL. */
            Location?: string;
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CreateInstanceAcceptedResponse'];
          };
        };
        /** @description Instance ID already exists. */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Creation admission is closed or the bounded creation queue is full. */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    /** Get one instance with its live classified container status. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Instance metadata. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Instance'];
          };
        };
        404: components['responses']['NotFound'];
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    /** Irreversibly delete one instance, its managed container, jobs, artifacts, backups, recovery volumes, and all managed data. */
    delete: {
      parameters: {
        query: {
          /** @description Must be true because instance deletion always purges managed data. */
          confirm: true;
          /** @description Audit reason for irreversible instance deletion; at most 512 characters. */
          reason: string;
        };
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Delete result. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeleteInstanceResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get instance status. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Status response. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['InstanceStatusResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/limits': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update CPU, memory, and disk limits for an instance. */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['LimitsRequest'];
        };
      };
      responses: {
        /** @description Updated instance metadata. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Instance'];
          };
        };
        /** @description An enabled CPU, memory, or disk allocation guard rejected a limit increase. Limit decreases remain allowed. */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components['responses']['ApiError'];
      };
    };
    trace?: never;
  };
  '/api/instances/{instance_id}/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Reset an instance tenant password or API key.
     * @description Atomically rotates the database credential, recreates the managed container with its current image and existing data, validates the replacement credential, and attempts to restore the previous credential if any step fails. The instance must be running and experiences a brief connection interruption.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ResetInstancePasswordRequest'];
        };
      };
      responses: {
        /** @description Credential reset result. The password is never included. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ResetInstancePasswordResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    trace?: never;
  };
  '/api/instances/{instance_id}/reconcile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reconcile stored instance status with the container runtime. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Reconciled instance status. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['InstanceStatusResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/power': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Unified power API for start, stop, restart, and kill. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['PowerRequest'];
        };
      };
      responses: {
        /** @description Power action result. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PowerResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/image': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Pull and switch an instance to a new database image.
     * @description Same-major updates recreate the container on the existing volume. Major version changes require major_upgrade=true and run the safer export/import migration workflow where supported.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateInstanceImageRequest'];
        };
      };
      responses: {
        /** @description Image update result. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UpdateInstanceImageResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    trace?: never;
  };
  '/api/admin/resources': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List resource usage for all instances. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Resource reports. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ResourceReport'][];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/resources/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get node capacity, allocation, and whole-host resource pressure.
     * @description Allocation includes all managed instances, including stopped instances that may be restarted. Host usage covers the entire Linux node. Managed usage is null when any running or booting instance could not be sampled. Disk totals describe the filesystem backing paths.volumes.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Node-wide resource summary for scheduling and capacity decisions. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['NodeResourceSummary'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/resources': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get resource usage for one instance. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Resource report. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ResourceReport'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get recent logs for one instance. */
    get: {
      parameters: {
        query?: {
          tail?: number;
        };
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Log output. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LogsResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Export one instance to a protocol-native dump artifact. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['ExportRequest'];
        };
      };
      responses: {
        /** @description Queued export job. */
        202: {
          headers: {
            /** @description Origin-relative job status URL. */
            Location?: string;
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ImportExportJob'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/import': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload a temporary dump or queue an import into one instance.
     * @description application/octet-stream stores, hashes, and returns a temporary upload without starting an import. application/json queues an import from an artifact, typed remote source, or ready temporary upload. Temporary uploads are separate from generated artifacts.
     */
    post: {
      parameters: {
        query?: never;
        header?: {
          /** @description Required for application/octet-stream and must exactly equal the bytes sent. */
          'Content-Length'?: number;
          /** @description Required for application/octet-stream. Percent-encoded UTF-8 flat filename, at most 180 decoded bytes, with a supported native dump extension. Paths and traversal components are rejected. */
          'X-DBEV-Filename'?: string;
          /** @description Optional expected digest for application/octet-stream; exactly 64 lowercase hexadecimal characters. */
          'X-DBEV-SHA256'?: string;
        };
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ImportRequest'];
          'application/octet-stream': string;
        };
      };
      responses: {
        /** @description Temporary upload committed, hashed, and ready for inspection or full import; no import job was started. */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ImportUpload'];
          };
        };
        /** @description Queued import job. */
        202: {
          headers: {
            /** @description Origin-relative job status URL. */
            Location?: string;
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ImportExportJob'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/import/uploads': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List active temporary import uploads for one instance.
     * @description Returns at most 100 instance-owned records. Temporary uploads never appear in the artifact inventory.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Temporary upload list. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ImportUpload'][];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/import/uploads/{upload_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get one temporary import upload belonging to an instance. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
          upload_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Temporary upload state and optional cached inspection catalog. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ImportUpload'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    /**
     * Cancel and durably delete one temporary import upload.
     * @description Importing uploads return a conflict. Deletion never removes a DBEV-generated artifact or operator-staged import file.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
          upload_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Upload deleted. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ImportUploadDeleteResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/import/uploads/{upload_id}/catalog': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Inspect a ready temporary dump and cache its bounded catalog.
     * @description Validates the archive wrapper and extracts a bounded metadata-only catalog without executing dump content. Inspection is lazy and idempotent once cached. The selective_supported response field is the authoritative capability; v0.5.1 uploads are full-import only. A concurrency rejection or bounded inspection limit leaves the upload ready, so a full import remains available.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
          upload_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Upload with cached dump inspection. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ImportUpload'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/import-export/jobs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List import/export jobs for one instance. */
    get: {
      parameters: {
        query?: {
          status?: string;
          limit?: number;
        };
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Job list. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ImportExportJob'][];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/import-export/jobs/{job_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get one import/export job belonging to an instance. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
          job_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Job. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ImportExportJob'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/backups': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List backups belonging to one instance. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Backup artifact list. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['StoredArtifact'][];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    /** Run a backup for one instance. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Completed backup artifact. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['StoredArtifact'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/backups/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get automatic backup configuration status. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Backup status. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BackupStatusResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/backups/run': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run backups for all eligible instances. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Completed backups and skipped instances. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['RunBackupsResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/backups/{backup_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete one backup belonging to an instance. */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
          backup_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Delete result. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeleteArtifactResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/backups/{backup_id}/contents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Browse the bounded schema catalog and captured row previews stored with a backup.
     * @description Existing backups created before catalog capture return catalog_available=false. The endpoint never starts a restored database or executes queries against backup files.
     */
    get: {
      parameters: {
        query?: {
          /** @description Exact object id returned by the objects list, such as public.users. */
          object?: string;
          offset?: number;
          limit?: number;
        };
        header?: never;
        path: {
          instance_id: string;
          backup_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Backup catalog, with an optional bounded preview selection. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BackupContentsResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/backups/{backup_id}/download': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
        backup_id: string;
      };
      cookie?: never;
    };
    /**
     * Download a backup using its temporary URL.
     * @description The stream is admitted under node-wide and transport-peer concurrency caps. A 429 response does not consume a single-use ticket.
     */
    get: {
      parameters: {
        query: {
          token: string;
        };
        header?: never;
        path: {
          instance_id: string;
          backup_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Backup file stream. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    /** Create a temporary download URL for one instance backup. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
          backup_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateDownloadRequest'];
        };
      };
      responses: {
        /** @description Temporary download URL. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DownloadUrlResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/backups/{backup_id}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore one backup into the same instance that owns it. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
          backup_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['DestructiveActionConfirmation'];
        };
      };
      responses: {
        /** @description Completed restore result. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['RestoreBackupResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/artifacts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List export artifacts belonging to one instance. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Artifact list. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['StoredArtifact'][];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/artifacts/{artifact_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete one export artifact belonging to an instance. */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
          artifact_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Delete result. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeleteArtifactResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/artifacts/{artifact_id}/download': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
        artifact_id: string;
      };
      cookie?: never;
    };
    /**
     * Download an artifact using its temporary URL.
     * @description The stream is admitted under node-wide and transport-peer concurrency caps. A 429 response does not consume a single-use ticket.
     */
    get: {
      parameters: {
        query: {
          token: string;
        };
        header?: never;
        path: {
          instance_id: string;
          artifact_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Artifact file stream. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    /** Create a temporary download URL for one instance artifact. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
          artifact_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateDownloadRequest'];
        };
      };
      responses: {
        /** @description Temporary download URL. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DownloadUrlResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/artifacts/retention': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply artifact retention for one instance. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted artifact IDs. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['RetentionResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/recovery/failed-jobs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List failed import/export jobs across the node. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Failed job list. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ImportExportJob'][];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/recovery/jobs/{job_id}/retry': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Retry a failed export or artifact import from its sanitized replay options. Credential imports and legacy jobs must be resubmitted. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
          job_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Replacement job. */
        202: {
          headers: {
            /** @description Origin-relative replacement job status URL. */
            Location?: string;
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ImportExportJob'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/instances/{instance_id}/recovery/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore an export artifact belonging to the same instance. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            artifact_id: string;
            confirm: boolean;
            reason: string;
          };
        };
      };
      responses: {
        /** @description Queued restore job. */
        202: {
          headers: {
            /** @description Origin-relative restore job status URL. */
            Location?: string;
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ImportExportJob'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/ws-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Issue short-lived WebSocket JWT for monitoring/log streams. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['WsTokenRequest'];
        };
      };
      responses: {
        /** @description WebSocket token. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WsTokenResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/images/pull': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Pull an image for a protocol. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            protocol: components['schemas']['Protocol'];
            image?: string | null;
          };
        };
      };
      responses: {
        /** @description Pull result. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PullImageResponse'];
          };
        };
        default: components['responses']['ApiError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ws/monitoring': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * WebSocket stream of instance resource snapshots.
     * @description Requires a short-lived WebSocket JWT with monitor:read. Non-browser clients may send Authorization: Bearer <jwt>. Browser clients should use Sec-WebSocket-Protocol with ["dbe.jwt", "<jwt>"]. Query-string tokens are rejected. Messages and frames are limited to 16 KiB. Full snapshots are emitted every 500 ms and include current instance stats plus install_progress entries for create, image-update, and major-upgrade operations. Each instance includes configured limits plus live usage fields: cpu_usage_percent, memory_usage_bytes, memory_limit_bytes, disk_used_bytes, network_rx_bytes, network_tx_bytes, and a resources object matching GET /api/instances/{instance_id}/resources. Network RX/TX are cumulative bytes observed at the authenticated gateway-to-backend boundary since daemon boot.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description WebSocket upgrade. */
        101: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ws/instances/{instance_id}/logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * WebSocket stream of container logs for one instance.
     * @description Requires a short-lived WebSocket JWT with logs:read. Non-browser clients may send Authorization: Bearer <jwt>. Browser clients should use Sec-WebSocket-Protocol with ["dbe.jwt", "<jwt>"]. Query-string tokens are rejected. Messages and frames are limited to 16 KiB.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description WebSocket upgrade. */
        101: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ws/instances/{instance_id}/import-export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * WebSocket stream of import/export jobs for one instance.
     * @description Requires a short-lived WebSocket JWT with import-export:read and access to the instance in the path. Messages and frames are limited to 16 KiB.
     */
    get: {
      parameters: {
        query?: {
          job_id?: string;
        };
        header?: never;
        path: {
          instance_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description WebSocket upgrade. */
        101: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components['responses']['ApiError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    Protocol: 'postgres' | 'redis' | 'valkey' | 'mariadb' | 'mysql' | 'mongodb' | 'clickhouse' | 'qdrant';
    LimitsRequest: {
      /** @example 0.5 */
      cpu_cores: number;
      /** @example 512 */
      memory_mib: number;
      /** @example 1024 */
      disk_mib: number;
    };
    InstanceLimits: components['schemas']['LimitsRequest'] & {
      disk_enforced?: boolean;
      /** @example host_filesystem_quota */
      disk_enforcement_method?: string;
    };
    CreateInstanceRequest: {
      /** @example inst_server_123_pg */
      instance_id: string;
      protocol: components['schemas']['Protocol'];
      /** @example server_123 */
      database: string;
      /** @example app_server_123 */
      username: string;
      /**
       * Format: password
       * @description Tenant database password or, for Qdrant, API key. DBE rejects NUL and line-break characters; Qdrant keys must also be valid HTTP header values.
       */
      password: string;
      /** @example db.example.com */
      public_host: string;
      /** @example 5434 */
      public_port?: number | null;
      /**
       * @description Optional pinned container image for this instance. The image must be the configured default or listed in images.allowed.<protocol>; omit this field to use the node default.
       * @example postgres:18.4
       */
      image?: string | null;
      /** @example server-123 */
      project_id?: string | null;
      limits?: components['schemas']['LimitsRequest'];
      /**
       * @description Irreversibly remove an orphaned container and persistent paths for this instance_id before retrying creation. Requires purge_stale_resources_confirmation.
       * @default false
       */
      purge_stale_resources: boolean;
      purge_stale_resources_confirmation?: components['schemas']['DestructiveActionConfirmation'] | null;
    };
    Instance: {
      schema_version: number;
      instance_id: string;
      protocol: components['schemas']['Protocol'];
      /** @enum {string} */
      status: 'creating' | 'booting' | 'running' | 'stopped' | 'failed' | 'quarantined' | 'deleting';
      public: {
        host: string;
        port: number;
      };
      /** @description Active instances use unix_socket. docker_tcp is returned only for legacy records quarantined during migration and is never connected. */
      backend:
        | {
            /** @constant */
            kind: 'unix_socket';
            socket_path: string;
          }
        | {
            /** @constant */
            kind: 'docker_tcp';
            host: string;
            port: number;
          };
      runtime: {
        /** @example docker */
        kind: string;
        container_name: string;
        /** @constant */
        network_mode: 'none';
      };
      database: {
        name: string;
        username: string;
      };
      /** @description Optional SHA-256 fingerprint of the instance gateway route key. */
      route_key_sha256?: string;
      limits: components['schemas']['InstanceLimits'];
      image?: {
        current: string | null;
        configured: string;
        update_available: boolean;
      };
      database_version?: {
        current: string | null;
        error: components['schemas']['PublicDiagnostic'] | null;
      };
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    SystemResponse: {
      /** @constant */
      service: 'databases-everywhere';
      version: string;
      /** @example 0.12.0 */
      api_version: string;
      /**
       * @description Readiness of the management API itself. Database listener readiness is reported separately under gateways.
       * @constant
       */
      api_readiness: 'ready';
      uuid: string;
      token_id: string;
      /** Format: uri */
      remote: string;
      api_host: string;
      api_port: number;
      api_bind: string;
      api_ssl_enabled: boolean;
      /** @description Fixed-window request allowance for each authenticated credential and transport-peer IP. */
      api_rate_limit_per_minute: number;
      /** @constant */
      api_rate_limit_scope: 'credential_and_peer_ip';
      /** @enum {string} */
      daemon_engine: 'docker' | 'podman';
      daemon_socket: string;
      /** @constant */
      database_container_network_mode: 'none';
      /** @constant */
      database_backend_transport: 'unix_socket';
      daemon_disk_limits_enforced: boolean;
      disk_mode: string;
      /** @description Whether create and limit-increase admission prevents configured CPU reservations from exceeding detected host cores. */
      prevent_cpu_overallocation: boolean;
      /** @description Whether create and limit-increase admission enforces the configured memory pool and reserve. */
      prevent_memory_overallocation: boolean;
      /** @description Whether create and limit-increase admission enforces the configured disk pool and reserve. */
      prevent_disk_overallocation: boolean;
      /** @description Whether this node accepts credential-based remote import sources. */
      remote_import_enabled: boolean;
      postgres_enabled: boolean;
      redis_enabled: boolean;
      valkey_enabled: boolean;
      mariadb_enabled: boolean;
      mysql_enabled: boolean;
      mongodb_enabled: boolean;
      clickhouse_enabled: boolean;
      clickhouse_http_enabled: boolean;
      clickhouse_http_bind: string;
      clickhouse_http_port: number;
      qdrant_enabled: boolean;
      gateways: components['schemas']['GatewayReadiness'];
    };
    HeartbeatResponse: {
      /** @constant */
      status: 'ok';
    };
    ImportExportJobResourceCost: {
      input_size_bytes: number;
      memory_mib: number;
      io_mib: number;
      cpu_units: number;
    };
    ImportExportSchedulerCapacity: {
      /** @enum {string} */
      mode: 'dynamic' | 'manual';
      max_active_jobs: number;
      memory_budget_mib: number;
      io_budget_mib: number;
      cpu_units: number;
    };
    ImportExportSchedulerSnapshot: {
      capacity: components['schemas']['ImportExportSchedulerCapacity'];
      active_jobs: number;
      waiting_jobs: number;
      active_memory_mib: number;
      active_io_mib: number;
      active_cpu_units: number;
      accepting: boolean;
    };
    ImportExportSchedulerRecommendation: {
      scheduler: components['schemas']['ImportExportSchedulerSnapshot'];
      estimate: components['schemas']['ImportExportJobResourceCost'];
      /** @description Mode-independent resource-model concurrency for jobs with the requested characteristics, bounded by dynamic_max_active_jobs. Zero is a valid safety result when the live memory budget cannot fit one modelled job; clients must not clamp it to one. CPU and I/O are concurrency weights, so a memory-safe job that exceeds either whole weight budget is recommended as one isolated job. In manual mode, compare it with scheduler.capacity.max_active_jobs, which is the actual fixed ceiling. */
      recommended_active_jobs: number;
      /** @description Current node-wide durable jobs and synchronous data operations holding queue admission, including work still waiting for an instance lock. */
      admitted_jobs: number;
      max_queued_jobs: number;
      max_queued_jobs_per_instance: number;
    };
    GatewayReadiness: {
      /** @enum {string} */
      status: 'starting' | 'ready' | 'failed' | 'stopping';
      expected_listeners: number;
      ready_listeners: number;
      failure?: string;
    };
    InstanceStatusResponse: {
      instance_id: string;
      /** @enum {string} */
      status: 'creating' | 'booting' | 'running' | 'stopped' | 'failed' | 'quarantined' | 'deleting';
      progress?: components['schemas']['InstallProgress'];
    };
    CreateInstanceAcceptedResponse: {
      instance_id: string;
      /** @constant */
      status: 'creating';
      /** @description Origin-relative URL for polling creation status and progress. */
      status_url: string;
    };
    InstallProgress: {
      instance_id: string;
      protocol: components['schemas']['Protocol'];
      /** @enum {string} */
      action: 'create' | 'image_update' | 'major_upgrade';
      /** @enum {string} */
      status: 'running' | 'completed' | 'failed';
      stage: string;
      message: string;
      image: string | null;
      layer: string | null;
      current: number | null;
      total: number | null;
      percent: number | null;
      diagnostic?: components['schemas']['PublicDiagnostic'];
      /** Format: date-time */
      updated_at: string;
    };
    DeleteInstanceResponse: {
      instance_id: string;
      deleted: boolean;
      purged: boolean;
    };
    Error: {
      error: string;
      code: string;
      /**
       * Format: uuid
       * @description Opaque support identifier included only for server-side failures.
       */
      error_id?: string;
    };
    PublicDiagnostic: {
      code: string;
      message: string;
      /**
       * Format: uuid
       * @description Opaque identifier for correlating an internal asynchronous failure with daemon logs.
       */
      error_id?: string;
    };
    ImportRequest: {
      source:
        | components['schemas']['ArtifactImportSource']
        | components['schemas']['RemoteImportSource']
        | components['schemas']['UploadImportSource'];
      /**
       * @description For nonphysical imports, merge replaces source-named objects/keys/collections while preserving target-only data; wipe clears the target database first. Redis, Valkey, and Qdrant artifact imports and uploads always replace the complete physical database, so mode does not change their behavior.
       * @default merge
       * @enum {string}
       */
      mode: 'merge' | 'wipe';
      selection?: components['schemas']['ImportExportSelection'];
    };
    ExportRequest: {
      /**
       * @description Optional outer wrapper. MongoDB plain output is already a native gzip archive, so gzip is normalized to plain instead of creating a double-gzip artifact. Redis, Valkey, and Qdrant accept only plain.
       * @enum {string|null}
       */
      archive_format?: 'plain' | 'gzip' | 'bzip2' | null;
      selection?: components['schemas']['ImportExportSelection'];
    };
    ArtifactImportSource: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'artifact';
      /** @description ID returned by this instance's artifacts endpoint, or the filename of an operator-staged file under paths.imports/<instance_id>/. */
      artifact_id: string;
      /**
       * @description Archive wrapper to remove before import. Omit for an unwrapped dump and for Redis/Valkey/Qdrant physical archives.
       * @enum {string|null}
       */
      archive_format?: 'plain' | 'gzip' | 'bzip2' | 'tar' | 'tar.gz' | 'zip' | null;
    };
    /** @description A temporary dump received through the octet-stream form of this instance's import endpoint. The daemon uses the persisted, inspected archive format; clients cannot override it. A successful import consumes and deletes the upload. A failed import releases it for retry until it is cancelled or expires. MongoDB uploads use source_database so one archive namespace can be selected and remapped without restoring other databases; DBEV may infer it from an inspected, complete, single-candidate catalog. */
    UploadImportSource: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'upload';
      /** @description Opaque ID returned by a successful temporary dump upload. */
      upload_id: string;
      /**
       * @description Original database namespace in a MongoDB archive. Rejected for every other protocol. It may be omitted only when the persisted inspection catalog is complete and has exactly one candidate; multiple or inconclusive candidates require an explicit value. DBEV restores only this namespace and remaps it to the target. The value must occupy 1-63 UTF-8 bytes and cannot contain NUL, slash, backslash, dot, space, double quote, or dollar sign.
       * @example legacy_tenant
       */
      source_database?: string;
    };
    /** @description Protocol-specific remote credentials. Qdrant imports also migrate aliases attached to selected source collections; source aliases win same-name conflicts. */
    RemoteImportSource: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'remote';
      /**
       * @description DNS name or literal IP only after surrounding whitespace is removed; URLs, paths, userinfo, and embedded ports are rejected.
       * @example source-db.example.com
       */
      host: string;
      /** @description Optional protocol port. A TLS-aware protocol default is used when omitted. */
      port?: number | null;
      /**
       * @description Verified TLS is the default. Plaintext also requires security.remote_import.allow_plaintext on the node.
       * @default true
       */
      tls: boolean;
      /** @description Required for PostgreSQL, MariaDB, MySQL, MongoDB, and ClickHouse. The trimmed value must occupy 1-256 UTF-8 bytes and contain no control characters. Omit for Redis, Valkey, and Qdrant. MariaDB/MySQL additionally allow at most 64 characters. MongoDB applies a 63-byte limit and rejects slash, backslash, dot, space, double quote, and dollar sign. ClickHouse additionally requires at most 128 ASCII letters, digits, underscores, or dashes. */
      database?: string | null;
      /** @description Required for SQL/ClickHouse. The trimmed value must occupy 1-256 UTF-8 bytes and contain no control characters. Optional with password for MongoDB, Redis, and Valkey ACL authentication. */
      username?: string | null;
      /**
       * Format: password
       * @description Source credentials are limited to 4096 UTF-8 bytes and are not stored in durable job records or metadata. SQL, MongoDB, and ClickHouse acquisition may place this value in a mode-0600 job-private temporary file that is removed immediately after the helper exits; Redis and Valkey keep it in process memory. SQL passwords cannot contain NUL, CR, or LF.
       */
      password?: string | null;
      /** @description Optional MongoDB authentication database. It follows MongoDB's 63-byte database-name restrictions or may be exactly $external. Defaults to database and is accepted only when username and password are both supplied. */
      authentication_database?: string | null;
      /** @description Redis or Valkey logical database index. Defaults to 0. */
      database_index?: number | null;
      /**
       * Format: password
       * @description Optional Qdrant API key limited to 4096 UTF-8 bytes, kept in process memory, and not stored in a credential file, durable job record, or job metadata. It must be a syntactically valid HTTP header value and permit cluster-topology, collection, and alias reads plus snapshot creation, download, and cleanup.
       */
      api_key?: string | null;
    };
    ImportExportSelection: {
      /**
       * @default full
       * @enum {string}
       */
      mode: 'full' | 'selective';
      /** @description Required and non-empty when mode is selective. MongoDB credential imports accept multiple collection names; MongoDB exports accept exactly one. */
      include?: string[];
      exclude?: string[];
      /** @description The complete replayable job options document is limited to 65536 encoded bytes. */
      fields?: {
        [key: string]: string[];
      };
    };
    ImportUpload: {
      upload_id: string;
      instance_id: string;
      /** @description Display-only flat filename supplied in X-DBEV-Filename; never a host path. */
      original_filename: string;
      protocol: components['schemas']['Protocol'];
      /**
       * @description Persisted wrapper selection. Catalog inspection verifies and may refine this value.
       * @enum {string|null}
       */
      archive_format: 'plain' | 'gzip' | 'bzip2' | 'tar' | 'tar.gz' | 'zip' | null;
      /** @enum {string} */
      state: 'uploading' | 'uploaded' | 'processing' | 'ready' | 'failed' | 'importing' | 'consumed' | 'deleting';
      size_bytes: number;
      /** @description Daemon-computed digest; null only while reception has not committed. */
      sha256: string | null;
      catalog?: components['schemas']['DumpInspection'];
      /** @description Safe diagnostic for the most recent upload or inspection failure. */
      error?: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: date-time */
      expires_at: string;
    };
    DumpInspection: {
      protocol: components['schemas']['Protocol'];
      sha256: string;
      source_size_bytes: number;
      /** @enum {string} */
      detected_archive_format: 'plain' | 'gzip' | 'bzip2' | 'tar' | 'tar.gz' | 'zip';
      /** @enum {string} */
      selection_kind: 'tables' | 'collections' | 'full_only';
      /** @description The only authoritative switch for enabling selective-import controls. */
      selective_supported: boolean;
      /** @description False when the bounded inspector could not enumerate every relevant catalog item. */
      catalog_complete: boolean;
      /** @description For MongoDB uploads, sorted source database candidates discovered from the bounded native archive prelude; otherwise protocol-specific namespace hints or an empty list. Treat this list as authoritative only when catalog_complete is true; an incomplete list may contain partial hints. */
      namespaces: string[];
      objects: components['schemas']['DumpSelectableObject'][];
      unselectable_object_count: number;
      /** @description Human-readable reason selective import is unavailable. */
      selective_unavailable_reason?: string;
    };
    DumpSelectableObject: {
      /** @enum {string} */
      kind: 'table' | 'collection';
      name: string;
      namespace?: string;
      /** @description Exact opaque value to send in selection.include or selection.exclude if selective_supported is true. */
      selection_key: string;
    };
    ImportUploadDeleteResponse: {
      upload_id: string;
      deleted: boolean;
    };
    ImportExportJob: {
      job_id: string;
      instance_id: string;
      /** @enum {string} */
      action: 'export' | 'import';
      /** @enum {string} */
      status: 'queued' | 'running' | 'succeeded' | 'failed';
      artifact_id: string | null;
      artifact_size_bytes: number | null;
      error: components['schemas']['PublicDiagnostic'] | null;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    StoredArtifact: {
      id: string;
      instance_id: string;
      size_bytes: number;
      /** Format: date-time */
      modified_at: string;
      sha256: string;
    };
    CreateDownloadRequest: {
      /** @default 120 */
      expires_in_seconds: number;
      /** @default true */
      single_use: boolean;
    };
    DownloadUrlResponse: {
      /** @description Origin-relative temporary download URL containing the short-lived capability. */
      url: string;
      expires_at_unix: number;
      single_use: boolean;
    };
    DeleteArtifactResponse: {
      id: string;
      deleted: boolean;
    };
    RetentionResponse: {
      deleted: string[];
    };
    BackupStatusResponse: {
      enabled: boolean;
      interval_minutes: number;
      run_on_startup: boolean;
      retention_keep_latest_per_instance: number;
      retention_max_age_days: number;
      redis_excluded: boolean;
      /** @enum {string} */
      storage_driver: 'local' | 's3' | 'kopia';
      browsing_enabled: boolean;
    };
    BackupCatalogColumn: {
      name: string;
      data_type: string;
      nullable: boolean;
      ordinal: number;
    };
    BackupObjectSummary: {
      id: string;
      namespace: string;
      name: string;
      kind: string;
      estimated_rows: number | null;
      columns: components['schemas']['BackupCatalogColumn'][];
      captured_preview_rows: number;
      preview_truncated: boolean;
    };
    BackupObjectSelection: {
      object_id: string;
      offset: number;
      limit: number;
      returned: number;
      total_captured: number;
      rows: unknown[];
      truncated: boolean;
    };
    BackupContentsResponse: {
      backup_id: string;
      instance_id: string;
      protocol: components['schemas']['Protocol'];
      database_name: string;
      /** Format: date-time */
      captured_at: string | null;
      consistency: string | null;
      catalog_available: boolean;
      truncated: boolean;
      warnings: string[];
      objects: components['schemas']['BackupObjectSummary'][];
      selection: components['schemas']['BackupObjectSelection'] | null;
    };
    SkippedBackup: {
      instance_id: string;
      protocol: components['schemas']['Protocol'];
      reason: components['schemas']['PublicDiagnostic'];
    };
    RunBackupsResponse: {
      backups: components['schemas']['StoredArtifact'][];
      skipped: components['schemas']['SkippedBackup'][];
    };
    RestoreBackupResponse: {
      instance_id: string;
      backup_id: string;
      restored: boolean;
    };
    DestructiveActionConfirmation: {
      /** @constant */
      confirm: true;
      reason: string;
    };
    WsTokenRequest: {
      subject: string;
      /**
       * @example [
       *       "monitor:read"
       *     ]
       */
      scopes: ('monitor:read' | 'logs:read' | 'import-export:read')[];
      /**
       * @description Explicit instance allow-list. Must be non-empty unless all_instances is true.
       * @default []
       */
      instances: string[];
      /**
       * @description Explicitly grants node-wide instance access and cannot be combined with a non-empty instances list.
       * @default false
       */
      all_instances: boolean;
      /** @default 900 */
      ttl_seconds: number;
    };
    WsTokenResponse: {
      /** @constant */
      token_type: 'Bearer';
      token: string;
      expires_at_unix: number;
    };
    PowerRequest: {
      /** @enum {string} */
      action: 'start' | 'stop' | 'restart' | 'kill';
    };
    PowerResponse: {
      /** @enum {string} */
      action: 'start' | 'stop' | 'restart' | 'kill';
      instance: components['schemas']['Instance'];
    };
    ResetInstancePasswordRequest: {
      /**
       * Format: password
       * @description New tenant database password or, for Qdrant, API key. It is never returned; DBE stores it only in its encrypted private credential repository for rollback and future managed recreation.
       */
      password: string;
    };
    ResetInstancePasswordResponse: {
      instance: components['schemas']['Instance'];
      /** @description True only when immutable startup credentials require container recreation (ClickHouse, Qdrant, and one-time migration of legacy Redis/Valkey instances without a stored encrypted credential); false for native in-place rotation. */
      restarted: boolean;
    };
    UpdateInstanceImageRequest: {
      /**
       * @description Pinned target image. Must be the configured default image or listed in images.allowed.<protocol>. Bare images and latest tags are rejected.
       * @example mongo:8.3.4
       */
      image: string;
      /**
       * Format: password
       * @description Current tenant database password. Used only as a compatibility fallback for legacy instances that predate encrypted tenant credential storage; current instances use their protected stored credential.
       */
      password?: string | null;
      /**
       * @description Set true only after an explicit admin confirmation when the image changes database major version. DBE then runs its export/import migration workflow instead of a same-volume recreate.
       * @default false
       */
      major_upgrade: boolean;
    };
    /** @enum {string} */
    ImageUpdateStrategy: 'in_place_recreate' | 'major_upgrade_migration';
    UpdateInstanceImageResponse: {
      instance?: components['schemas']['Instance'];
      /** @description Target image applied to the instance. */
      image?: string;
      recreated?: boolean;
      strategy?: components['schemas']['ImageUpdateStrategy'];
      /** @description Provider-style warnings the panel should show after a successful upgrade. */
      warnings?: string[];
      /** @description Logical export artifact kept after a major upgrade for rollback/audit. */
      export_artifact_id?: string | null;
      /** @description Whether the old volume was retained on the node for manual rollback. */
      old_volume_backup_retained?: boolean;
    };
    ConfigPatchResponse: {
      applied: boolean;
      restart_required: boolean;
      config_path: string;
    };
    LogsResponse: {
      instance_id: string;
      stdout: string;
      stderr: string;
    };
    ResourceReport: {
      instance_id: string;
      protocol: string;
      status: string;
      cpu: {
        configured_cores: number;
        usage_percent: number | null;
      };
      memory: {
        configured_mib: number;
        usage_bytes: number | null;
        limit_bytes: number | null;
      };
      disk: {
        configured_mib: number;
        limit_bytes: number;
        used_bytes: number;
        enforced: boolean;
        enforcement_method: string;
        /** @enum {string} */
        enforcement_strength: 'hard' | 'soft' | 'none';
        scanner_logical_bytes?: number;
        scanner_physical_bytes?: number;
        scanner_growth_bytes_per_second?: number;
        scanner_peak_growth_bytes_per_second?: number;
        scanner_predicted_seconds_to_limit?: number;
        scanner_stop_threshold_bytes?: number;
        scanner_recovery_threshold_bytes?: number;
        scanner_restart_blocked?: boolean;
        scanner_sample_age_seconds?: number;
      };
      network: {
        rx_bytes: number | null;
        tx_bytes: number | null;
      };
    };
    NodeResourceSummary: {
      node_uuid: string;
      /** Format: date-time */
      sampled_at: string;
      cpu: {
        total_cores: number;
        allocated_cores: number;
        host_usage_percent: number;
        managed_usage_cores: number | null;
      };
      memory: {
        total_bytes: number;
        allocation_limit_bytes: number;
        reserved_bytes: number;
        allocated_bytes: number;
        host_used_bytes: number;
        managed_used_bytes: number | null;
        available_bytes: number;
      };
      disk: {
        total_bytes: number;
        allocation_limit_bytes: number;
        reserved_bytes: number;
        allocated_bytes: number;
        host_used_bytes: number;
        managed_used_bytes: number | null;
        available_bytes: number;
      };
      instances: {
        total: number;
        creating: number;
        booting: number;
        running: number;
        stopped: number;
        failed: number;
        quarantined: number;
        deleting: number;
      };
    };
    PullImageResponse: {
      protocol: components['schemas']['Protocol'];
      image: string;
      pulled: boolean;
    };
  };
  responses: {
    /** @description Request rejection or server-side failure. Internal details are logged under error_id and are never returned to clients. */
    ApiError: {
      headers: {
        /** @description Opaque support identifier included for server-side failures. */
        'X-Error-Id'?: string;
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Missing, invalid, or insufficient bearer token. */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Resource not found. */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
